### ISSUE TITLE
Is there a requirements.txt file?

### ISSUE THREAD

**Issue by frank-ceballos** [zeiss-microscopy/OAD#12]
Thanks for creating this amazing repo. I have learned so much just by starting at your code. However, I can't run your Jupyter Notebooks. I was wondering if you could provide a requirements.txt file to alleviate my problem. So far I have pip installed all the dependencies but I can't read the czi images because the packages I install are not compatible with each other. I will appreciate any of your help to resolve this problem.

-Frank

**Comment by zeissmicroscopy** [comment]
Archived
