### ISSUE TITLE
hello world script for the macro editor?

### ISSUE THREAD

**Issue by jackyko1991** [zeiss-microscopy/OAD#43]
Hello Zeiss engineers,

Thank you for the open source repository for the Zen development. I am recently get involved in setting up smart microscopes and image processing on Zeiss products for better integration of existing workflow.

When I comes to the documentation and this repo, the rich content is quite confusing for me to start with, even with the tutorial PDFs.

Would there be a hello world example to show how image can be retrieved from Zen then work with numpy? This will be a great help for the beginners.

If possible can I call custom conda environment as external python?

**Comment by CamachoDejay** [comment]
Hej @jackyko1991 
Do you want to open the image inside ZEN and then work with it using numpy? or do you want to use an external image analysis pipeline running in python to open the .czi image?

For the latter I think this discussion is very userfull: https://forum.image.sc/t/reading-czi-file-in-python/39768/15
you can use either pylibCZIrw: https://pypi.org/project/pylibCZIrw/ or aicspylibczi https://pypi.org/project/aicspylibczi/

Regarding minimal examples I am interested in collecting them here: https://github.com/CamachoDejay/Zeiss-OAD-examples/tree/main 

My current example might be out of your scope, but I will be placing more in the future.

**Comment by jackyko1991** [comment]
@sebi06 looks these libraries are promising. But are they come with Zen version of Iron python?

guess from what you suggest, the proper way of using these libraries are
1. using macro editor in Zen to prepare the necessary metadata
2. parse the image path and metadata info to anaconda python as cli arguments, then spawn child process under Zen (how to deal with virtual environments in this sense?)
3. process the image in external python
4. save the processed result to local
5. using Zen macro to automatically load back the data

with this pipeline, I guess some of the image processing can offload to more powerful servers (or WSL2 for deep learning task on "windows" ) via restful api? (image data can be stored on network drive but not local)

When handling TB of data is quite a pain for the typical Zen users, I am trying to streamline the process with as few io as possible. Apologize if some topics are out of the original scope of Zen.

**Comment by sebi06** [comment]
Hi @jackyko1991 

All those libraies have nothing to do with ZEN or IronPython and are meant to be used from a normal conda environment.

What is possible is to call an external python script from within ZEN Macro (if this helps your workflow). Examples can be found here: 

https://github.com/zeiss-microscopy/OAD/tree/master/Scripts/Start_External_Software

But I would really consider to also think about doing the whole workflow directly in Python and to create new CZI if needed. pylibCZIrw also supports to write new CZI files.
