### ISSUE TITLE
colormap

### ISSUE THREAD

**Issue by MathieuFallet** [zeiss-microscopy/OAD#7]
Thanks to share this work. I was trying to display my 3D image with napari, you did it !
The jupyter notebook "read and display images using napari " for czi files do not find the colormap for each channel. Is there an issue for that ? 
This information doesn't seem to be in he meta data that you show In [11] of the notebook.
I try with my  six channels czi image (no time, around 300Mo) , I can open the image but the 3D view have quite a lot of bug to display my image..
Thanks, Mathieu

**Comment by zeissmicroscopy** [comment]
Archived
